### ISSUE TITLE
pwgen may be used with secure option

### ISSUE THREAD

**Issue by lgrebe-sys** [mbernhardtSys11/openstack-helpers#3]
https://github.com/matthiasbernhardt/openstack-helpers/blob/867b333c99e3f3e7aa7b4c20bbb4f70b5ebee5d8/secretgen.sh#L14

```
-s, --secure
    Generate completely random, hard-to-memorize passwords. These should only be used for machine passwords, since otherwise it's almost guaranteed that users will simply write the password on a piece of paper taped to the monitor... 
```

Your naming colleague approached me as he was wondering that running pwgen without secure option somehow generates passwords containing more vocals than usual.

`pwgen -s 32 1`

A quick fix I guess =)

**Comment by matthiasbernhardt** [comment]
You may have noticed, that the passwords are 32 characters long. Quoting additional resources from our password policy:

* https://xkcd.com/936/
* https://security.stackexchange.com/questions/6095/xkcd-936-short-complex-password-or-long-dictionary-passphrase
* https://www.baekdal.com/insights/password-security-usability

A longer password is both strong and safe, while a "safe" but short password is rather more problematic than really safer. You can argue that long _and_ "safe" would be even better but the point is, that I want to avoid problematic characters and 32 is already _mora than twice as long_ as requested by our policy. Feel free to change the initial password on receipt (recommended anyway), but I'd rather stick to the same standards. My namesake already has a reputation for confusing perceived with real security at the cost of safety and usability (count the number of redundant "factors" you need to login to a certain system maintained by him).
